services:
  elixir:
    image: elixir:1.16
    tty: true
    volumes:
      - .:/home/app:cached
      - elixir_deps:/home/app/deps
      - elixir_build:/home/app/_build
      - elixir_ls:/home/app/.elixir_ls
    working_dir: /home/app

volumes:
  elixir_deps:
  elixir_build:
  elixir_ls:
